import { prisma } from "./prisma";
import type { EmailResult, EmailStatus } from "./email/types";
import type {
  BetaInvitationDeliveryStatus,
  BetaInvitationDeliveryTrigger,
} from "@/app/generated/prisma/client";

/**
 * Persisted, immutable delivery-attempt history for beta invitation email
 * (#175). One row is written for every real invocation of the invitation
 * email transport — never fabricated, never backfilled for pre-feature
 * invitations (those render an explicit "Not recorded" state instead).
 *
 * Callers (deliverBetaInvitationEmail / deliverBetaInvitationEmailWithClaim
 * in betaInvitation.ts) must only call {@link recordBetaInvitationDeliveryAttempt}
 * with a real, already-observed `EmailResult` — this module never talks to a
 * transport and never decides whether to send anything.
 */

const FAILURE_REASON_MAX_LENGTH = 300;
const PROVIDER_MESSAGE_ID_MAX_LENGTH = 200;

/** Used when a FAILED EmailResult didn't include a usable reason string. */
export const GENERIC_DELIVERY_FAILURE_REASON = "Delivery failed";

/** Used when the acting user could not be resolved (should not happen in practice). */
const UNKNOWN_ACTOR_EMAIL = "Unknown (deleted)";

export type BetaInvitationDeliveryTriggerInput = "issue" | "resend" | "reissue";

/**
 * Strip control/newline characters and bound length before persisting a
 * failure reason. Defense-in-depth: the transport contract (ResendTransport,
 * LoggingTransport) already guarantees `EmailResult.error` never carries a
 * token, full email body, or raw provider payload — only a short message.
 *
 * Returns `null` for an empty/missing input; callers apply the generic
 * fallback reason themselves so a bare `{ status: "failed" }` result still
 * records instead of silently failing the audit insert's CHECK constraint.
 */
export function sanitizeDeliveryFailureReason(
  raw: string | undefined | null,
): string | null {
  if (!raw) {
    return null;
  }

  const cleaned = raw.replace(/[\u0000-\u001F\u007F]+/g, " ").trim();

  if (!cleaned) {
    return null;
  }

  return cleaned.slice(0, FAILURE_REASON_MAX_LENGTH);
}

/** Bound a provider message id before persisting. Returns `null` for empty input. */
export function boundProviderMessageId(
  raw: string | undefined | null,
): string | null {
  if (!raw) {
    return null;
  }

  const trimmed = raw.trim();

  if (!trimmed) {
    return null;
  }

  return trimmed.slice(0, PROVIDER_MESSAGE_ID_MAX_LENGTH);
}

function mapTrigger(
  trigger: BetaInvitationDeliveryTriggerInput,
): BetaInvitationDeliveryTrigger {
  switch (trigger) {
    case "issue":
      return "ISSUE";
    case "resend":
      return "RESEND";
    case "reissue":
      return "REISSUE";
  }
}

function mapEmailStatus(status: EmailStatus): BetaInvitationDeliveryStatus {
  switch (status) {
    case "sent":
      return "SENT";
    case "failed":
      return "FAILED";
    case "skipped":
      return "SKIPPED";
  }
}

/**
 * Canonicalize an EmailResult + trigger into a persistable attempt row, then
 * insert it. Never throws — an audit-write failure (or actor-lookup failure)
 * is logged and swallowed so it can never change what the caller returns to
 * the user. This means a database outage landing between a successful
 * transport call and this insert can produce an *unrecorded* (not
 * mis-recorded) attempt; see ADR-014's outbox-deferral addendum.
 *
 * `requestId` must be generated by the caller *before* invoking the
 * transport, since it is also threaded into `EmailMetadata` so transport
 * console logs correlate to the row this function persists.
 */
export async function recordBetaInvitationDeliveryAttempt(params: {
  invitationId: string;
  trigger: BetaInvitationDeliveryTriggerInput;
  result: EmailResult;
  attemptedByUserId: string;
  requestId: string;
}): Promise<void> {
  const { invitationId, trigger, result, attemptedByUserId, requestId } = params;

  try {
    const user = await prisma.user.findUnique({
      where: { id: attemptedByUserId },
      select: { email: true, displayName: true },
    });

    const attemptedByEmail = user?.email ?? UNKNOWN_ACTOR_EMAIL;
    const attemptedByDisplayName = user?.displayName ?? null;

    const failureReason =
      result.status === "failed"
        ? (sanitizeDeliveryFailureReason(result.error) ??
          GENERIC_DELIVERY_FAILURE_REASON)
        : null;

    const providerMessageId =
      result.status === "sent" ? boundProviderMessageId(result.messageId) : null;

    await prisma.betaInvitationDeliveryAttempt.create({
      data: {
        invitationId,
        trigger: mapTrigger(trigger),
        status: mapEmailStatus(result.status),
        providerMessageId,
        failureReason,
        attemptedByUserId,
        attemptedByEmail,
        attemptedByDisplayName,
        requestId,
      },
    });
  } catch (error) {
    console.error(
      "[betaInvitationDelivery] Failed to persist delivery attempt",
      { invitationId, trigger, requestId, error },
    );
  }
}
