#!/usr/bin/env tsx
/**
 * Setup E2E Test Environment Variables
 *
 * This script queries the database to find test data and outputs
 * the environment variables needed to run E2E tests.
 *
 * Usage:
 *   npx tsx scripts/setup-e2e-env.ts
 *   npx tsx scripts/setup-e2e-env.ts > .env.test
 */
import "dotenv/config";
import { prisma } from "@/app/src/lib/prisma";

async function main() {
  console.error("Querying database for test data...\n");

  // Find the primary test alliance (DAY1)
  const alliance = await prisma.alliance.findFirst({
    where: { name: "DAY1" },
    include: {
      allianceMembers: {
        where: { archivedAt: null },
        take: 1,
      },
      memberships: {
        include: { user: true },
        where: { role: "OWNER" },
        take: 1,
      },
    },
  });

  if (!alliance) {
    console.error("❌ No test alliance found. Run `npm run seedDb` first.");
    process.exit(1);
  }

  const owner = alliance.memberships[0]?.user;
  const member = alliance.allianceMembers[0];

  if (!owner) {
    console.error("❌ No owner found for test alliance.");
    process.exit(1);
  }

  if (!member) {
    console.error("❌ No member found for test alliance.");
    process.exit(1);
  }

  // Find a second alliance for tenant isolation tests (or create indicator that it's needed)
  const otherAlliance = await prisma.alliance.findFirst({
    where: {
      id: { not: alliance.id },
    },
  });

  // Find users with different roles for permission matrix tests
  const adminMembership = await prisma.allianceMembership.findFirst({
    where: { allianceId: alliance.id, role: "ADMIN" },
    include: { user: true },
  });

  const leaderMembership = await prisma.allianceMembership.findFirst({
    where: { allianceId: alliance.id, role: "LEADER" },
    include: { user: true },
  });

  const viewerMembership = await prisma.allianceMembership.findFirst({
    where: { allianceId: alliance.id, role: "VIEWER" },
    include: { user: true },
  });

  // Platform admin is configured via PLATFORM_ADMIN_EMAILS env var
  // We'll look for a user with the expected test email
  const platformAdmin = await prisma.user.findFirst({
    where: { email: "platform-admin@test.local" },
  });

  // Output environment variables
  console.log("# E2E Test Environment Variables");
  console.log("# Generated by scripts/setup-e2e-env.ts");
  console.log(`# Generated at: ${new Date().toISOString()}`);
  console.log("");
  console.log("# Primary test alliance");
  console.log(`TEST_ALLIANCE_ID=${alliance.id}`);
  console.log(`TEST_MEMBER_ID=${member.id}`);
  console.log("");
  console.log("# Owner credentials");
  console.log(`TEST_OWNER_EMAIL=${owner.email}`);
  console.log(`TEST_OWNER_PASSWORD=Password123`);
  console.log("");

  if (otherAlliance) {
    console.log("# Other alliance (for tenant isolation tests)");
    console.log(`TEST_OTHER_ALLIANCE_ID=${otherAlliance.id}`);
    console.log("");
  } else {
    console.error(
      "⚠️  No second alliance found for tenant isolation tests. Consider creating one."
    );
  }

  if (adminMembership) {
    console.log("# Admin credentials");
    console.log(`TEST_ADMIN_EMAIL=${adminMembership.user.email}`);
    console.log(`TEST_ADMIN_PASSWORD=Password123`);
    console.log("");
  } else {
    console.error(
      "⚠️  No ADMIN user found. Create one for permission matrix tests."
    );
  }

  if (leaderMembership) {
    console.log("# Leader credentials");
    console.log(`TEST_LEADER_EMAIL=${leaderMembership.user.email}`);
    console.log(`TEST_LEADER_PASSWORD=Password123`);
    console.log("");
  } else {
    console.error(
      "⚠️  No LEADER user found. Create one for permission matrix tests."
    );
  }

  if (viewerMembership) {
    console.log("# Viewer credentials");
    console.log(`TEST_VIEWER_EMAIL=${viewerMembership.user.email}`);
    console.log(`TEST_VIEWER_PASSWORD=Password123`);
    console.log("");
  } else {
    console.error(
      "⚠️  No VIEWER user found. Create one for permission matrix tests."
    );
  }

  if (platformAdmin) {
    console.log("# Platform admin credentials");
    console.log(`TEST_PLATFORM_ADMIN_EMAIL=${platformAdmin.email}`);
    console.log(`TEST_PLATFORM_ADMIN_PASSWORD=Password123`);
    console.log("");
    console.log("# Add this to your main .env to enable E2E platform admin access:");
    console.log(`PLATFORM_ADMIN_EMAILS_E2E=${platformAdmin.email}`);
    console.log("");
  } else {
    console.error(
      "⚠️  No platform admin found. Create one for platform dashboard tests."
    );
  }

  console.error("\n✅ Environment variables generated successfully!");
  console.error("Add these to your .env.test file or export them before running E2E tests.");
}

main()
  .catch((e) => {
    console.error("Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
